const mongoose = require("mongoose");

/**
 * A training-completion certificate. One certificate per (training, user)
 * pair — issuance is idempotent, see services/certificate.service.js.
 *
 * Almost every field here is a SNAPSHOT taken at issuance time (userName,
 * employeeId, department, plaza, trainingTitle, trainerName, etc.) so a
 * printed/verified certificate keeps reading correctly even if the source
 * User/Training record is later renamed, reassigned, or edited. Never
 * displayed on the certificate or the public verify page: Mongo _id values
 * (other than the human-readable certificateNumber), JWTs, internal API
 * payloads, or Cloudinary asset ids — see utils/certificatePdf.js and
 * pages/VerifyCertificatePage.jsx in the frontend, which only read the
 * fields intentionally exposed here.
 *
 * `status` only ever persists "active" or "revoked" — there is no
 * background job flipping certificates to "expired" on a timer. Instead,
 * "expired" is a derived, read-time state (status === "active" AND
 * expiresAt is in the past); see toCertificateView() in
 * services/certificate.service.js, which every route response goes
 * through so the VALID / EXPIRED / REVOKED wording shown to users is
 * computed consistently in one place.
 */
const certificateSchema = new mongoose.Schema(
  {
    certificateNumber: { type: String, required: true, unique: true, index: true },
    verificationCode: { type: String, required: true, unique: true, index: true },

    // --- Employee snapshot ---
    user: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
    userName: { type: String, required: true },
    employeeId: { type: String, default: "" },
    employeeRole: { type: String, default: "" },
    department: { type: String, default: "" },
    plaza: { type: String, default: "" },

    // --- Training snapshot ---
    training: { type: mongoose.Schema.Types.ObjectId, ref: "Training", required: true },
    trainingTitle: { type: String, required: true },
    trainingCategory: { type: String, default: "" },
    trainingConcept: { type: String, default: "" },
    trainerName: { type: String, default: "" },
    durationMinutes: { type: Number, default: null },

    // --- Assessment / completion snapshot ---
    trainingDate: { type: Date, default: null },
    completedAt: { type: Date, required: true },
    completionPercentage: { type: Number, default: 100 },
    assessmentScore: { type: Number, default: null },
    passingScore: { type: Number, default: null },
    result: { type: String, enum: ["Passed", "Failed", "Not Assessed"], default: "Not Assessed" },

    // --- Certificate lifecycle ---
    issuedAt: { type: Date, default: Date.now },
    expiresAt: { type: Date, default: null },
    validityMonths: { type: Number, default: null },
    signatoryName: { type: String, default: "" },
    signatoryTitle: { type: String, default: "Authorized Signatory - HSE Department" },
    status: { type: String, enum: ["active", "revoked"], default: "active" },
    revokedAt: { type: Date, default: null },
    revokedReason: { type: String, default: "" },
    revokedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null },
    revokedByName: { type: String, default: "" },

    // Who/how the certificate came to exist — "Generated By" / "Generated
    // Date" in the certificate history view (section 11 of the spec).
    generatedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null },
    generatedByName: { type: String, default: "" },
    generationMode: { type: String, enum: ["manual", "system"], default: "manual" }
  },
  { timestamps: true }
);

certificateSchema.index({ user: 1, createdAt: -1 });
certificateSchema.index({ training: 1, user: 1 }, { unique: true });
certificateSchema.index({ status: 1, expiresAt: 1 });

module.exports = mongoose.model("Certificate", certificateSchema);
