import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const reportColumns = {
  work: [
    { header: "Date", keys: ["Date", "date", "createdAt"] },
    { header: "Work Type", keys: ["Work Type", "workType", "title"] },
    { header: "Location", keys: ["Location", "location"] },
    { header: "Workers Count", keys: ["Workers Count", "workersCount"] },
    { header: "Status", keys: ["Status", "status"] },
    { header: "Approved By", keys: ["Approved By", "approvedBy"] }
  ],
  hazard: [
    { header: "Date", keys: ["Date", "date", "createdAt"] },
    { header: "Plaza", keys: ["Plaza", "plaza"] },
    { header: "Location", keys: ["Location", "location"] },
    { header: "Reported By", keys: ["Reported By", "reportedBy"] },
    { header: "Category", keys: ["Category", "category"] },
    { header: "Action Team", keys: ["Action Team", "Action", "action"] },
    { header: "Status", keys: ["Status", "status"] }
  ],
  training: [
    { header: "Training Title", keys: ["Training Title", "Title", "title"] },
    { header: "Trainer", keys: ["Trainer", "trainer", "uploadedBy"] },
    { header: "Category", keys: ["Category", "category"] },
    { header: "Uploaded Date", keys: ["Uploaded Date", "Date", "createdAt", "uploadedAt"] },
    { header: "Status", keys: ["Status", "status"] }
  ]
};

const safeValue = (value) => {
  if (value === undefined || value === null || value === "") return "-";
  if (typeof value === "object") {
    if (value.name) return value.name;
    if (value.email) return value.email;
    return "-";
  }
  return String(value);
};

const pickValue = (row, keys = []) => {
  for (const key of keys) {
    if (row[key] !== undefined && row[key] !== null && row[key] !== "") return safeValue(row[key]);
  }
  return "-";
};

export const normalizeReportRowsByType = (rows = [], type = "work") => {
  const columns = reportColumns[type] || reportColumns.work;
  return rows.map((row) =>
    columns.reduce((acc, column) => {
      acc[column.header] = pickValue(row, column.keys);
      return acc;
    }, {})
  );
};

const formatGeneratedDate = (value) =>
  new Date(value).toLocaleString("en-IN", {
    day: "2-digit",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit"
  });

export const exportReportPdf = ({
  rows = [],
  type = "work",
  reportTitle = "Report",
  companyName = "Sasthan Udupi Tollway Pvt Ltd",
  companyLogo,
  generatedBy = "System",
  generatedAt = new Date()
}) => {
  const normalizedRows = normalizeReportRowsByType(rows, type);
  if (!normalizedRows.length) return false;

  const columns = reportColumns[type] || reportColumns.work;
  const headers = columns.map((column) => column.header);
  const body = normalizedRows.map((row) => headers.map((header) => row[header] ?? "-"));

  const doc = new jsPDF("landscape");
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const generatedDateText = formatGeneratedDate(generatedAt);

  autoTable(doc, {
    startY: 56,
    margin: { top: 56, bottom: 16, left: 14, right: 14 },
    head: [headers],
    body,
    styles: { fontSize: 8.5, cellPadding: 2.5 },
    headStyles: { fillColor: [15, 23, 42], textColor: [241, 245, 249] }
  });

  const totalPages = doc.internal.getNumberOfPages();
  for (let page = 1; page <= totalPages; page += 1) {
    doc.setPage(page);

    doc.setFontSize(13);
    doc.setTextColor(15, 23, 42);
    doc.text(companyName, 14, 14);
    doc.setFontSize(10);
    doc.text(reportTitle, 14, 22);
    doc.setFontSize(9);
    doc.text(`Generated By: ${generatedBy}`, 14, 29);
    doc.text(`Generated: ${generatedDateText}`, 14, 35);

    if (companyLogo) {
      try {
        doc.addImage(companyLogo, "PNG", pageWidth - 34, 10, 20, 20);
      } catch (_error) {
        // If image embedding fails in this browser context, PDF generation should still continue.
      }
    }

    doc.setFontSize(9);
    doc.text(`Page ${page} of ${totalPages}`, pageWidth - 14, pageHeight - 8, { align: "right" });
    doc.text(`Generated: ${generatedDateText}`, 14, pageHeight - 8);
  }

  doc.save(`${type}_report.pdf`);
  return true;
};

